services:
  db:
    image: postgres:17.1
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME_SECRET}
      POSTGRES_USER: ${DB_USER_SECRET}
      POSTGRES_PASSWORD: ${DB_PASSWORD_SECRET}
    ports:
      - "${DB_PORT_SECRET}:5432"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - pg_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  db_data:
  pg_data:
